"""Outer carrier transport skeleton for Paracci envelopes."""

from .base import (
    CARRIER_PUBLIC_ERROR,
    MAX_CARRIER_FILE_BYTES,
    MAX_CARRIER_IMAGE_DIMENSION,
    MAX_CARRIER_IMAGE_FRAMES,
    MAX_CARRIER_IMAGE_PIXELS,
    MAX_EXTRACTED_MESSAGE_BYTES,
    MAX_EXTRACTED_SETUP_BYTES,
    PLANNED_CARRIER_KINDS,
    PNG_LOSSLESS_V1,
    QR_MATRIX_V1,
    CapacityEstimate,
    CarrierAdapter,
    CarrierAdapterError,
    CarrierDetection,
    CarrierError,
    CarrierExtraction,
    CarrierLimitError,
    CarrierOutput,
    CarrierRegistryError,
    CarrierUnsupportedError,
)
from .registry import (
    detect_carrier,
    embed_envelope,
    estimate_capacity,
    extract_envelope,
    get_adapter,
    register_adapter,
    registered_kinds,
)

__all__ = [
    "CARRIER_PUBLIC_ERROR",
    "MAX_CARRIER_FILE_BYTES",
    "MAX_CARRIER_IMAGE_DIMENSION",
    "MAX_CARRIER_IMAGE_FRAMES",
    "MAX_CARRIER_IMAGE_PIXELS",
    "MAX_EXTRACTED_MESSAGE_BYTES",
    "MAX_EXTRACTED_SETUP_BYTES",
    "PLANNED_CARRIER_KINDS",
    "PNG_LOSSLESS_V1",
    "QR_MATRIX_V1",
    "CapacityEstimate",
    "CarrierAdapter",
    "CarrierAdapterError",
    "CarrierDetection",
    "CarrierError",
    "CarrierExtraction",
    "CarrierLimitError",
    "CarrierOutput",
    "CarrierRegistryError",
    "CarrierUnsupportedError",
    "detect_carrier",
    "embed_envelope",
    "estimate_capacity",
    "extract_envelope",
    "get_adapter",
    "register_adapter",
    "registered_kinds",
]
